CREATE DATABASE AVALIACAO
USE AVALIACAO
CREATE TABLE Veiculos
( ID		BIGINT			NOT NULL  AUTO_INCREMENT PRIMARY KEY, 
  PLACA 	VARCHAR(8)  	NOT NULL,
  MODELO 	VARCHAR(20) 	NOT NULL,
  MARCA		VARCHAR(200)	NOT NULL,
  COR	 	VARCHAR(15) 	NOT NULL,
  PRECO 	FLOAT	 		NOT NULL);

DROP TABLE Veiculos

